import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/layouts/Header/Header";
import { Theme } from "@/Theme/Theme";
import 'ag-grid-community/styles/ag-grid.css'; // Core grid CSS, always needed
import { TransactionProvider } from "@/Context/TransactionContext";
import TandstackProvider from "@/Provider/TandstackProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Expense Tracker",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  
  return (
    <html lang="en">
      <Theme>
        <TandstackProvider>
        <TransactionProvider>
          <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Header/>
        {children}
      </body>
      </TransactionProvider>
      </TandstackProvider>
      </Theme>
    </html>
  );
}
